//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by OpenGL.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_OPENGLTYPE                  129
#define IDD_LIGHTS_DLG                  134
#define IDD_MATERIAL_DLG                136
#define IDD_MOUSE_SENSIVIITY            140
#define IDD_FogDialog                   142
#define IDD_TEXTUREDIALOG               145
#define IDC_LIGHT_SPACE                 1010
#define IDC_RADIO_LIGHT1                1017
#define IDC_RADIO_LIGHT2                1018
#define IDC_RADIO_LIGHT3                1019
#define IDC_RADIO_LIGHT4                1020
#define IDC_RADIO_LIGHT5                1021
#define IDC_RADIO_LIGHT6                1022
#define IDC_RADIO_LIGHT7                1023
#define IDC_RADIO_LIGHT8                1024
#define IDC_AMBL_COLOR_R                1025
#define IDC_LIGHT_ENABLED               1026
#define IDC_AMBL_COLOR_G                1027
#define IDC_AMBL_COLOR_B                1028
#define IDC_LIGHT_COLOR_R               1029
#define IDC_LIGHT_COLOR_G               1030
#define IDC_LIGHT_COLOR_B               1031
#define IDC_LIGHT_POS_X                 1032
#define IDC_LIGHT_POS_Y                 1033
#define IDC_LIGHT_POS_Z                 1034
#define IDC_LIGHT_DIR_X                 1035
#define IDC_LIGHT_DIR_Y                 1036
#define IDC_LIGHT_DIR_Z                 1037
#define IDC_LIGHT_TYPE                  1038
#define IDC_MATERIAL_AMBIENT            1039
#define IDC_MATERIAL_DIFFUSE            1040
#define IDC_MATERIAL_SHININESS          1041
#define IDC_SLIDER2                     1041
#define IDC_SLIDER1                     1041
#define IDC_MOUSESLIDER                 1041
#define IDC_MATERIAL_SPECULAR           1042
#define IDC_EDIT1                       1042
#define IDC_EDIT2                       1044
#define IDC_EDIT3                       1045
#define IDC_COMBO1                      1046
#define IDC_EDIT4                       1047
#define IDC_CHECK1                      1048
#define IDC_COMBO2                      1053
#define IDC_CHECK2                      1054
#define IDC_COMBO3                      1055
#define IDC_COMBO4                      1056
#define IDC_EDIT5                       1057
#define IDC_EDIT6                       1058
#define IDC_EDIT7                       1059
#define IDC_EDIT8                       1060
#define IDC_EDIT9                       1061
#define IDC_OBJSELECT                   1062
#define IDC_FILENAME                    1063
#define IDC_BROWSE                      1064
#define ID_FILE_LOAD                    32771
#define ID_VIEW_ORTHOGRAPHIC            32772
#define ID_VIEW_PERSPECTIVE             32773
#define ID_ACTION_ROTATE                32774
#define ID_ACTION_TRANSLATE             32775
#define ID_ACTION_SCALE                 32776
#define ID_AXIS_X                       32777
#define ID_AXIS_Y                       32778
#define ID_AXIS_Z                       32779
#define ID_LIGHT_SHADING_FLAT           32781
#define ID_LIGHT_SHADING_GOURAUD        32782
#define ID_LIGHT_CONSTANTS              32783
#define ID_ANIM_PLAY                    32793
#define ID_ANIM_CLEAR                   32794
#define ID_ANIM_SNAPSHOT                32795
#define ID_BUTTON_SUBDIVIDE             32797
#define ID_OPTIONS_PERSPECTIVECONTROL   32798
#define ID_OPTIONS_MOUSESENSITIVITY     32799
#define ID_ACTION_DSDS                  32802
#define ID_ACTION_DFDFG                 32803
#define ID_ACTION_VIEWSPACE             32804
#define ID_ACTION_OBJECTSPACE           32805
#define ID_OPTIONS_CHANGEWIRECOLOR      32806
#define ID_OPTIONS_CHANGEBACKGROUNDCOLOR 32807
#define ID_OPTIONS_DRAWBOUNDINGBOX      32808
#define ID_BUTTON32809                  32809
#define ID_OPTIONS_SHOWVERTICESNORMALS  32810
#define ID_OPTIONS_SHOWFACESNORMALS     32811
#define ID_BUTTON32823                  32823
#define ID_OPTIONS_TORCH                32824
#define ID_BUTTON32825                  32825
#define ID_AXIS_XY                      32826
#define ID_FILE_RESET                   32829
#define ID_ACTION_UNIFORMSCALING        32831
#define ID_SHADING_WIREFRAME            32833
#define ID_MATERIAL_LOADTEXTURE         32834
#define ID_OPTIONS_BACKFACESCULLING     32835
#define ID_LIGHT_FOG                    32836
#define ID_MATERIAL_PROPERTIES          32837
#define ID_ACTION_TEXTURETRANSFORMATIONS 32839
#define ID_FILE_RESET32840              32840
#define ID_RESET_LIGHT                  32841
#define ID_RESET_VIEW                   32842
#define ID_MATERIAL_TESSELATION         32843
#define ID_MATERIAL_LOADMIPMAP          32844
#define ID_ADVANCED_LOADBACKGROUNG      32845
#define ID_ADVANCED_EXPORTIMAGE         32846
#define ID_ADVANCED_ADVA                32847
#define ID_ADVANCED_ADVANCEDSHADING     32848

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        146
#define _APS_NEXT_COMMAND_VALUE         32849
#define _APS_NEXT_CONTROL_VALUE         1065
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
